# Generated by Django 3.0.4 on 2020-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atcAccount', models.CharField(max_length=18)),
                ('atcPassword', models.CharField(max_length=8)),
            ],
        ),
    ]
