# Generated by Django 3.0.4 on 2020-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
