# Generated by Django 3.1.5 on 2021-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jichangfxkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=500)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=500)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=500)),
                ('frontdata11', models.CharField(max_length=30)),
                ('frontdata12', models.CharField(max_length=30)),
                ('frontdata13', models.CharField(max_length=500)),
                ('frontdata14', models.CharField(max_length=30)),
                ('frontdata15', models.CharField(max_length=30)),
                ('frontdata16', models.CharField(max_length=500)),
                ('frontdata17', models.CharField(max_length=30)),
                ('frontdata18', models.CharField(max_length=30)),
                ('frontdata19', models.CharField(max_length=500)),
                ('frontdata20', models.CharField(max_length=30)),
                ('frontdata21', models.CharField(max_length=500)),
                ('frontdata22', models.CharField(max_length=30)),
                ('frontdata23', models.CharField(max_length=30)),
            ],
        ),
    ]
