# Generated by Django 3.0.4 on 2021-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunliankaohe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCfxkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=30)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=30)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ACCgqkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=30)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=30)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='APPfxkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=30)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=30)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='APPgqkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=30)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=30)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='jichanggqkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=30)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=30)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata11',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata12',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata13',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata14',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata15',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata16',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata17',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata18',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata19',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata20',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata21',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata22',
        ),
        migrations.RemoveField(
            model_name='jichangfxkhb',
            name='frontdata23',
        ),
        migrations.AlterField(
            model_name='jichangfxkhb',
            name='frontdata10',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jichangfxkhb',
            name='frontdata4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jichangfxkhb',
            name='frontdata7',
            field=models.CharField(max_length=30),
        ),
    ]
