# Generated by Django 3.0.4 on 2021-08-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunliankaohe', '0002_auto_20210816_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCzgkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=30)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=30)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='APPzgkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=30)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=30)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='jichangzgkhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=100)),
                ('frontdata2', models.CharField(max_length=30)),
                ('frontdata3', models.CharField(max_length=30)),
                ('frontdata4', models.CharField(max_length=30)),
                ('frontdata5', models.CharField(max_length=30)),
                ('frontdata6', models.CharField(max_length=30)),
                ('frontdata7', models.CharField(max_length=30)),
                ('frontdata8', models.CharField(max_length=30)),
                ('frontdata9', models.CharField(max_length=30)),
                ('frontdata10', models.CharField(max_length=30)),
            ],
        ),
    ]
