# Generated by Django 3.0.4 on 2020-05-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainningcompletion', '0003_banzu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainningstatusdetail',
            name='frontdata13',
        ),
        migrations.RemoveField(
            model_name='trainningstatusdetail',
            name='frontdata14',
        ),
    ]
