# Generated by Django 3.0.4 on 2020-05-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evalution1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailevalution', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='evalution2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailevalution', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='evalution3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailevalution', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='evalution4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailevalution', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='evalution5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailevalution', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atcName', models.CharField(max_length=20)),
                ('atcOld', models.CharField(max_length=3)),
                ('基本信息', models.CharField(max_length=300)),
                ('管制员等级信息', models.CharField(max_length=300)),
                ('执照信息', models.CharField(max_length=300)),
                ('英语等级信息', models.CharField(max_length=300)),
                ('非管制学历信息', models.CharField(max_length=300)),
                ('管制学历信息', models.CharField(max_length=300)),
                ('管制工作经历信息', models.CharField(max_length=300)),
                ('体检信息', models.CharField(max_length=300)),
                ('奖励信息', models.CharField(max_length=300)),
                ('惩罚信息', models.CharField(max_length=300)),
                ('管制教员信息', models.CharField(max_length=300)),
                ('检查员信息', models.CharField(max_length=300)),
                ('检查员考核信息', models.CharField(max_length=300)),
                ('赴外培训信息', models.CharField(max_length=300)),
                ('岗位培训信息', models.CharField(max_length=300)),
                ('放单考核信息', models.CharField(max_length=300)),
                ('执照检查信息', models.CharField(max_length=300)),
                ('爱岗敬业信息', models.CharField(max_length=300)),
                ('职称信息', models.CharField(max_length=300)),
                ('特殊技能信息', models.CharField(max_length=300)),
                ('科室信息', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='saveevaluationresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=300)),
                ('训练情况', models.CharField(max_length=300)),
                ('教员评语', models.CharField(max_length=300)),
                ('studentname', models.CharField(max_length=300)),
                ('teachername', models.CharField(max_length=300)),
                ('selLocation11', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='trainningstatusdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=300)),
                ('frontdata2', models.CharField(max_length=300)),
                ('frontdata3', models.CharField(max_length=300)),
                ('frontdata4', models.CharField(max_length=300)),
                ('frontdata5', models.CharField(max_length=300)),
                ('frontdata6', models.CharField(max_length=300)),
                ('frontdata7', models.CharField(max_length=300)),
                ('frontdata8', models.CharField(max_length=300)),
                ('frontdata9', models.CharField(max_length=300)),
                ('frontdata10', models.CharField(max_length=300)),
                ('frontdata11', models.CharField(max_length=300)),
                ('frontdata12', models.CharField(max_length=300)),
                ('frontdata13', models.CharField(max_length=300)),
                ('frontdata14', models.CharField(max_length=300)),
                ('frontdata15', models.CharField(max_length=300)),
                ('frontdata16', models.CharField(max_length=300)),
            ],
        ),
    ]
