# Generated by Django 3.0.6 on 2020-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atcInfo', '0002_evalution1_evalution2_evalution3_evalution4_evalution5'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainningstatusdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdata1', models.CharField(max_length=300)),
                ('frontdata2', models.CharField(max_length=300)),
                ('frontdata3', models.CharField(max_length=300)),
                ('frontdata4', models.CharField(max_length=300)),
                ('frontdata5', models.CharField(max_length=300)),
                ('frontdata6', models.CharField(max_length=300)),
                ('frontdata7', models.CharField(max_length=300)),
                ('frontdata8', models.CharField(max_length=300)),
                ('frontdata9', models.CharField(max_length=300)),
                ('frontdata10', models.CharField(max_length=300)),
                ('frontdata11', models.CharField(max_length=300)),
                ('frontdata12', models.CharField(max_length=300)),
                ('frontdata13', models.CharField(max_length=300)),
                ('frontdata14', models.CharField(max_length=300)),
                ('frontdata15', models.CharField(max_length=300)),
                ('frontdata16', models.CharField(max_length=300)),
            ],
        ),
    ]
