from django.db import models


# python manage.py makemigrations atcInfo
# python manage.py migrate atcInfo
# Create your models here.
class info_00(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info(models.Model):
    atcName = models.CharField(max_length=20)
    atcOld = models.CharField(max_length=3)
    基本信息 = models.CharField(max_length=300, null=True)
    管制员等级信息 = models.CharField(max_length=300, null=True)
    执照信息 = models.CharField(max_length=300, null=True)
    英语等级信息 = models.CharField(max_length=300, null=True)
    非管制学历信息 = models.CharField(max_length=300, null=True)
    管制学历信息 = models.CharField(max_length=300, null=True)
    管制工作经历信息 = models.CharField(max_length=300, null=True)
    体检信息 = models.CharField(max_length=300, null=True)
    奖励信息 = models.CharField(max_length=300, null=True)
    惩罚信息 = models.CharField(max_length=300, null=True)
    管制教员信息 = models.CharField(max_length=300, null=True)
    检查员信息 = models.CharField(max_length=300, null=True)
    检查员考核信息 = models.CharField(max_length=300, null=True)
    赴外培训信息 = models.CharField(max_length=300, null=True)
    岗位培训信息 = models.CharField(max_length=300, null=True)
    放单考核信息 = models.CharField(max_length=300, null=True)
    执照检查信息 = models.CharField(max_length=300, null=True)
    爱岗敬业信息 = models.CharField(max_length=300, null=True)
    职称信息 = models.CharField(max_length=300, null=True)
    特殊技能信息 = models.CharField(max_length=300, null=True)
    科室信息 = models.CharField(max_length=300, null=True)
    班组信息 = models.CharField(max_length=300, null=True)


class info_01(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_02(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_03(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_04(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_05(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_06(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_07(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_08(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)
    data_21 = models.CharField(max_length=300, null=True)
    data_22 = models.CharField(max_length=300, null=True)
    data_23 = models.CharField(max_length=300, null=True)
    data_24 = models.CharField(max_length=300, null=True)
    data_25 = models.CharField(max_length=300, null=True)
    data_26 = models.CharField(max_length=300, null=True)
    data_27 = models.CharField(max_length=300, null=True)
    data_28 = models.CharField(max_length=300, null=True)
    data_29 = models.CharField(max_length=300, null=True)
    data_30 = models.CharField(max_length=300, null=True)


class info_09(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_10(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_11(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_12(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_13(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_14(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_15(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_16(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_17(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_18(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_19(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_20(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class info_21(models.Model):
    data_01 = models.CharField(max_length=300, null=True)
    data_02 = models.CharField(max_length=300, null=True)
    data_03 = models.CharField(max_length=300, null=True)
    data_04 = models.CharField(max_length=300, null=True)
    data_05 = models.CharField(max_length=300, null=True)
    data_06 = models.CharField(max_length=300, null=True)
    data_07 = models.CharField(max_length=300, null=True)
    data_08 = models.CharField(max_length=300, null=True)
    data_09 = models.CharField(max_length=300, null=True)
    data_10 = models.CharField(max_length=300, null=True)
    data_11 = models.CharField(max_length=300, null=True)
    data_12 = models.CharField(max_length=300, null=True)
    data_13 = models.CharField(max_length=300, null=True)
    data_14 = models.CharField(max_length=300, null=True)
    data_15 = models.CharField(max_length=300, null=True)
    data_16 = models.CharField(max_length=300, null=True)
    data_17 = models.CharField(max_length=300, null=True)
    data_18 = models.CharField(max_length=300, null=True)
    data_19 = models.CharField(max_length=300, null=True)
    data_20 = models.CharField(max_length=300, null=True)


class evalution1(models.Model):
    detailevalution = models.CharField(max_length=300, null=True)
    value = models.CharField(max_length=20, )


class evalution2(models.Model):
    detailevalution = models.CharField(max_length=300, null=True)
    value = models.CharField(max_length=20, )


class evalution3(models.Model):
    detailevalution = models.CharField(max_length=300, null=True)
    value = models.CharField(max_length=20, )


class evalution4(models.Model):
    detailevalution = models.CharField(max_length=300, null=True)
    value = models.CharField(max_length=20, )


class evalution5(models.Model):
    detailevalution = models.CharField(max_length=300, null=True)
    value = models.CharField(max_length=20, )


class saveevaluationresult(models.Model):
    score = models.CharField(max_length=300, null=True)
    训练情况 = models.CharField(max_length=300, null=True)
    教员评语 = models.CharField(max_length=300, null=True)
    studentname = models.CharField(max_length=300, null=True)
    teachername = models.CharField(max_length=300, null=True)
    selLocation11 = models.CharField(max_length=300, null=True)
